controllers:
    resource: ../../src/UI/Action/
    type: annotation

social:
    resource: ../../src/UI/Action/Social
    type: annotation

security:
    resource: ../../src/UI/Action/Security
    type: annotation

api:
    resource: ../../src/UI/Action/Api
    type: annotation