App\Domain\DTO\RegisterDTO:
    properties:
        email:
            - App\Validator\ExistingEmail:
                groups: [Register]

App\Domain\DTO\ForgottenPasswordDTO:
    properties:
        email:
            - App\Validator\NonExistingEmail:
                groups: [ForgottenPassword]

